---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle # The bundle name will also be used for the target
spec:
  sources:
    # Include a bundle of publicly trusted certificates which can be
    # used to validate most TLS certificates on the internet, such as
    # those issued by Let's Encrypt, Google, Amazon and others.
    # NB: Unless you pin the package providing these CAs, the default can change!
    - useDefaultCAs: true

    # A Secret in the "trust" namespace; see "Trust Namespace" below for further details
    - secret:
        name: 'root-secret'
        key: 'ca.crt'
  target:
    configMap:
      key: 'trust-bundle.pem'
    namespaceSelector:
      matchLabels:
        private-ca: 'enabled'
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: private-ca
spec:
  sources:
    - useDefaultCAs: false
    - secret:
        name: 'root-secret'
        key: 'ca.crt'
  target:
    configMap:
      key: 'private-ca.pem'
    namespaceSelector:
      matchLabels:
        private-ca: 'enabled'
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: operator-ca-tls-private
spec:
  sources:
    - useDefaultCAs: false
    - secret:
        name: 'root-secret'
        key: 'ca.crt'
  target:
    secret:
      key: 'ca.crt'
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: minio-operator
