---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root
  namespace: cert-manager
spec:
  isCA: true
  duration: 175200h # 20y
  renewBefore: 720h # 30d
  subject:
    organizations:
      - Root X1
    countries:
      - FI
  commonName: Root X1
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root
spec:
  ca:
    secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ecdsa
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - ECDSA
    countries:
      - FI
  commonName: ECDSA
  secretName: ecdsa-secret
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  issuerRef:
    kind: ClusterIssuer
    name: root
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ecdsa
spec:
  ca:
    secretName: ecdsa-secret
