---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCxIPBo9Py9t+U6rM4E0vs10jOXEiH53mxtV9e48zMWejkcVqkd5o3Cf8az5J+b7yJsOIXv5vfhbnukDFDAzRfuhXbadjZdwaqK90/DMCweYBr4wXw8nmsAsX8d8HO5HfsHCUMATIaAyyrsJIzgnxcCsc3rHtso5ZK5RzRiy+LUHJIVEBDyc7PIDZrW1yEGviOH/FJUtT27H2bWuKIHDbiIqcpkDKr4R5xy/OdeWZtea6A714g0gGcIhDtCbK17fWHQW9VB0I3CbW5K4JJyg856HD6xC/siP5ufBOvvtX9SLukZMetgdimMQupr9eKaYM0V+kmmDiH6DzO/O8GoUPLWgmVYCDLpbxgTzjchYv6IkcFGl2+vTNsAAiMaLGR/keWnD1niRYlPKD5HXU/CmWPnyqNMz+qAI6ec18Hz1EZ2CAXjCJF/WnDJQVziickv09j+colbr/5egRvBXJN3NLdxHbJZ7l3SgbyZRQP1S4c/0tsfW9l6qF6eFwLze8zDIVBIZXV05Vu2WhsKCsvtWYR9z2vVQMs9KKACq55EzpO+ng4O8Lim7XHlAeAtx3r4Abtl3wfv0GcwfVJU0CTzs4hx2C8vf3v0FDczUkOjUDpjQC8vRp3Mqsd8D84OfdYL3LFWN8haCQufI8ttjRjrUhzB6OOsmYaj3mJqN+lm0/1p5SVlFvdM/jZV3A+7zOTQo6d+zHSUnOjwZ6oPQQ4ofPUeq1JzDT2cqPMvDUYBM0zIcYFutkI8XTDI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
