apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudnative-pg
      version: '^0.22.1'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 24h
  install:
    crds: CreateReplace
  values:
    monitoring:
      podMonitorEnabled: false
      podMonitorAdditionalLabels:
        release: kube-prom-stack
      grafanaDashboard:
        create: true
        namespace: observability
        labels:
          # grafana_dashboard: '1' # use when the depreecated `sidecarLabel` and `sidecarLabelValue` removed
          app.kubernetes.io/instance: prometheus-community
