apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim-filesystem
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 0 * * *
  name: trim-filesystem
  task: filesystem-trim
  groups:
    - default
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 12 0 * * *
  groups:
    - default
  name: snapshot-cleanup
  task: snapshot-cleanup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: db-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 30 12 * * *
  groups:
    - database
  labels: {}
  name: db-backup
  retain: 7
  task: backup
