apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
spec:
  interval: 24h
  chart:
    spec:
      chart: reloader
      version: '^1.0.0'
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: default
      interval: 24h
