apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbeaver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      containers:
        - name: dbeaver
          image: dbeaver/cloudbeaver:24.3.0 # {"$imagepolicy": "default:dbeaver"}
          ports:
            - containerPort: 8978
          volumeMounts:
            - name: dbeaver-workspace
              mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: dbeaver-workspace
          persistentVolumeClaim:
            claimName: dbeaver-workspace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbeaver-workspace
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
