---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 24h
  chart:
    spec:
      chart: ingress-nginx
      version: '~4.11.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 24h
  values:
    controller:
      service:
        annotations:
          oci.oraclecloud.com/load-balancer-type: 'nlb'
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: 'ocid1.networksecuritygroup.oc1.uk-london-1.aaaaaaaayjfuwjyc2uwq4ig63xfnbe32imlxw2ntew5pcn52v4runub6zvjq'
      ingressClassResource:
        default: true
      config: { use-forwarded-headers: 'true' }
