apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 24h
  chart:
    spec:
      chart: trivy-operator
      version: '^0.24.1'
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
      interval: 24h
  values:
    serviceMonitor:
      # enabled determines whether a serviceMonitor should be deployed
      enabled: false
      labels:
        release: kube-prom-stack
    trivy:
      ignoreUnfixed: true
