---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 24h
  chart:
    spec:
      chart: loki-stack
      version: '^2.10.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 24h
  values:
    loki:
      isDefault: false
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
      image:
        tag: 2.9.10
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 24h
  chart:
    spec:
      chart: tempo
      version: '~1.12.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 24h
  values:
    tempoQuery:
      enabled: true
    persistence:
      enabled: false
    tempo:
      extraEnvFrom:
        - secretRef:
            name: tempo-env
        - configMapRef:
            name: tempo-env
      storage:
        trace:
          backend: s3
          s3:
            bucket: pi-k8s-tempo
            endpoint: s3.nl-ams.scw.cloud
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411 # this is needed for tempo to receive spans
