---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAvvkcQhQTSherR8vqYsAmldX7XGNxIiUfkLHRQSlrwS1mCst+ByLV1/6h2mRfFjCrx6lUuWfed0IygNVwwOnVDmXIxhMi+l1tdnFFPBL/oCCg9i3T6MRcYahHPSESI7qS/FHhmH7rM3nuZqqzv0YZcPJ4aICsJwcEI8KqGMvrQ8H5ODcUH3APyM1tH0s8fq7hkJhY5bXsw07JjSOw9cfq4CDdpYtblKlczZ3DrvZa8z4RHXggDD/OL89QAh6z5GO8OVFrkblgUnDvFJeWZgSEmBqNdZX1Dlz/tX2dfpnOFDcev60AMqOyVv7mDnW4KeMCpnATiS9MUnJasHzCXcZj6dTkwbSnnjOSzvbuRHjR0FjQVpjJsHxF+U994OAnncx/FGIgdftniGUJ5rfL/wATi4slVD2BWXyIEdVeZ7mdEDhlCzCFrERod0FLXhKiVyTqE8nTgNgnpevBTwFSaessQOz/GZiPCsTQyC8Xv7PbQq6hNc6tJvWlp7QLdVZjIs6wspyYppRnG9NjU9yM3TCf8qC+LsGXELQB8Re3phO/vhkCd2SR1w1KIm0/UuyMuQTEEDSOAUmGJm3AQNMqLsZNTplgptHz4YpEfILV/20WSsRbh6o9bEUth88GrVt60HjIgjwF3kjkI93j/5oUUSe/ISGOlftx+eN6UHCQTVWqRQkbACVP3by1Q+p955j1PxgE0ktwVgDSucUs95Bi3ZnwWFN9K1cWvSgUloPwTJuOL2bihO1pyEjsztWAXgQ==
    ADMIN_USER: AgC4MKS21hByA6D5sgSegftlgjxnMUyK06YFRZfEoeLfzt46f8zcuW6RBMbJcedMzDxb0Vyw/CrT4xK3pBF8vs1N5+piDeJGFD7J+beUYPEEvFjSj/IOkRqQEgTvL/addgJ7Ana6LbmqWsCdW0zpEaqPmTTwIrqbzsnMqC8sGNodJMCFFcM5Yge3nkY+N2MTNrs/YtwcttAFHo3Zd/2gIhThulAuNwmlQf6mNsjQEMGd67u9rjANvmt1IY8v2h2rGKBIA5R/8FbaHtXYiVfP9wsSxP28SQ0f5WK1vTDtPwlYiHB1CZH1HU2owfTR46nFTJl6WgF18Tpwf+EbiEGHsMSsgjrfFwPTgImMp82PeNXiJLOPd8TvMH39JjNbeEIZbvzbsmK9pX94SPbGkt0NXjoVmHZebYonvhu3lk4hCRWzVaG3jKpj8s4iHY25jygh2EOPuINxDqV5Er93gjPgCDFM3m9yk8os5yUYEeujOwDD9kUfbR8m5pdA0WqmwMXal0OVAEMWy7Y/h/HtVkdFkBbH5J8xrLf8uuIm6VjUEBtyC39NrFhGwbzCeM8DrBkmkKompEtMLT2UklBQtvqhSRGHRCqghqc8rRc4xx+a6m8QtxTVyuf91yx2pRP/uc0Pxu17CPNWULH/WEnJZdDNjentALVRyFpJfQHBar8qjj1qfwknd9peVQWPgZz4xg7dVS+HuBZzv4mR
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
