apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  interval: 24h
  chart:
    spec:
      chart: jaeger
      version: '^1.0.2'
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: observability
      interval: 24h
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
    storage:
      type: elasticsearch
    elasticsearch:
      replicas: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    collector:
      service:
        zipkin:
          enabled: true
          port: 9411
