---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: observability
spec:
  encryptedData:
    SLACK_API_URL: AgByln52fWmOD3x1/OmuAmbP+baYfYnNY/R1Al+6Q3TC/0xISia8Vor8VPgSwzp3sv2I1jHljag5oBMpf2Xks0KyOwmJScno5HR0PaK1V9wFvR9H7gmiEV1IrSFX1GDAdwi1N6na5yVcGY0WCIIBlJjnqqXsVLaVTxJdPBwKVvWchT7+t3WsQoHD5xALPaV3hfIfdMvIW7MLR6tnL8l70AiO9ZoYsmCGeMx2+yaZveQ+X8UXS7uL2zyuPFuIBDX2fKKJ8mkwFrGk4xO6F9oRcXgup2axtuiHDEcSpIUql+N0g1ZrMhN5tIdMS+ZlpMe2M20AOgz9N3IaJcheiJgkgh3Rd3cSOMBVDludhMqDqmC2iI7jNwwF9zYstOiptKGxuvihav9GMFJas1+XHohXMdtQ6uhFYYrDVFV+3exlRyVEeE+1JEmtgSUt0fKchhdyFXAbFFFQgxkpWoHOaflOzVh4XbO6VYOJwbCAX+554CFplITn1tQ2G/w1utZk8FBGF/cYX4Bl+5fxcge4PSYM8uXs91Bjmeo2KcrnUtIJDVk+ORQDAEhuvhYRgKoZWv8ZtC4d+KVcsJgS+m38tn/J4XLZM6BUXL7CG3UoCRIzSNXr3UQOIptQ6pRMhEueRMpZ2sH5+EmJkFNjMMn/VjspEyb3lVfSWxcad3yDfnjW/RFoOeZ0Z9KeqPcgbHvbb2IIJ7wnsS1avKLrP0jL3Eg5qZHAUHcXSbuyLFmqfpZKKyXGA8wraGhwXcrg0cOrHDS2wwsKN/TMogkTe53JK5UNvLvIaqGxJwDnwgIsA0/R/yqB
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: observability
