---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubereboot.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: kured
      version: '^5.6.0'
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: kube-system
      interval: 24h
  values:
    hostNetwork: false
    extraEnvVars:
      - name: KURED_NOTIFY_URL
        valueFrom:
          secretKeyRef:
            name: kured-env
            key: KURED_NOTIFY_URL
      - name: KURED_LOCK_RELEASE_DELAY
        value: 1h # 1h
      - name: KURED_DRAIN_POD_SELECTOR
        value: app!=csi-attacher,app!=csi-provisioner,longhorn.io/component!=instance-manager
      - name: KURED_PROMETHEUS_URL
        value: http://prometheus-operated.observability.svc.cluster.local:9090
      - name: KURED_ALERT_FILTER_REGEXP
        value: ^(RebootRequired|Watchdog)$
      - name: KURED_PRE_REBOOT_NODE_LABELS
        value: kured.io/reboot=true
      - name: KURED_POST_REBOOT_NODE_LABELS
        value: kured.io/reboot=false
      - name: KURED_PERIOD
        value: 1m # 1h
      - name: KURED_REBOOT_DELAY
        value: 15m # 15m
