apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: metrics-server
      version: '^3.12.2'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
      interval: 24h
  values:
    replicas: 2
