apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: s3
spec:
  interval: 24h
  chart:
    spec:
      chart: tenant # https://artifacthub.io/packages/helm/minio-operator/tenant
      version: '^7.0.0'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 24h
  values:
    tenant:
      name: s3
      configSecret:
        name: minio-env-configuration
        accessKey: false
        secretKey: false
        existingSecret: true
      users:
        - name: minio-user
      env:
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: EC:2
      pools:
        - servers: 6
          name: pool-0
          volumesPerServer: 1
          size: 500Gi
          storageClassName: longhorn-crypto-global
          tolerations:
            - key: 'node-role.kubernetes.io/control-plane'
              operator: 'Exists'
              effect: 'NoSchedule'
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: v1.min.io/tenant
                        operator: In
                        values:
                          - s3
                      - key: v1.min.io/pool
                        operator: In
                        values:
                          - pool-0
                  topologyKey: kubernetes.io/hostname
      buckets:
        - name: harrytang
      certificate:
        requestAutoCert: false
    ingress:
      api:
        enabled: true
        host: api.s3.harrytang.com
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - api.s3.harrytang.com
            secretName: harrytang-tls
      console:
        enabled: true
        host: console.s3.harrytang.com
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - console.s3.harrytang.com
            secretName: harrytang-tls
