---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 24h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: minio-operator
spec:
  interval: 24h
  chart:
    spec:
      chart: operator
      version: '^7.0.0'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 24h
