---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wai
  namespace: default
spec:
  imageRepositoryRef:
    name: wai
  policy:
    semver:
      range: '^1.5.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: dbeaver
  namespace: default
spec:
  imageRepositoryRef:
    name: dbeaver
  policy:
    semver:
      range: '^24.2.0'
