---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: wai
  namespace: default
spec:
  image: containous/whoami
  interval: 10m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dbeaver
  namespace: default
spec:
  image: dbeaver/cloudbeaver
  interval: 10m0s
