---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBhD0jOUqdWuFaNs+/9L+EdHzTiDRlqnIkuDCIfGbmQ5bnnzzr5z80MI8pjFLjVScefj3L0kvk/tqzxFtzv7VQht/z5Ct/m0k+YtIRYZRKG4wOR3MACuqufRgX6c+J3XGGpjs907FMU+837e3g+3S40aUsmbyijw/qwVJ32mtP6REiYbP5Bn/9gYpeOPQHUp07EW/sI12y2tlpjIxx3eqYCqq9NU9rL+Dztn1M9gOFx9x1VyWDGGLXXc5kh+2rs0Y9TQunztLfUjoYwBzBwnG4iYw9RquWG23VdAtIedwDLryKuNlbeUNAFMd6uSeXQQid2aI/A2vq041QSCXcEWw1PHp5/tD33tUoTjYKKRiPeIQO5N9LTefpW2dcBk2sWXddgKMNVz6OVZKRs4I6izwdmqWhQQAt67g0RCfyzXxVI/gz9dt8mOz4meeOCCqq/UIzWectg/f0WZflT8d6pXL3rHMdX8cduDqKyI3H5FpDHCjgjsDkoxeicf1n8H34dDv7ifdF8ZZs949tzBnfIfS+nKTcuGWNUE/+twjq+XTMCQWtSJs7XUYPWAwA/0DKISO9GBal6Sf0AvFX4G6NZ9tRS1SBqVPLorJRS1Kqp6ACVFVhWApPmCtEjJxUwSTGBvveQxfC0cetGsYAwrvAjm54byw7XaQU/UQmPB6Bf9R9Eh6lGc4CcPSzLhfY/Xg+sjc8BAgp9oPOsa66fGiteWLiKrA==
    client_secret: AgCzY2ytFk7zbBcNqoI9Sq+DZS523vSaPvjzKL5Tfi8oUx19C03pP+Z2q+QfHYPnphGbjliDFit0/lkCceDuQLAqLN8AdwKJhQSY1CHwnjX66ZYK+MtgoEiqJ7pMZYvgEquaaIlEjCOnBraF0qh0vdf83b/bnsulMHX2+r9ZKcexfiLcG3Y9oU/gHCTBVTT8T2ScGnmw8id1Ndxb+t9qx3BEEUk0woihgFsBLqouGS3MNB39wBgOzjZGgMCpPgYlJAYjUpgbU6/FtHgJ9VAeGQ6WgjEXj6hjlgii4M3bepBuIbgkFRZSJW2qo+c0BA+nm6gjmuvef1XxdfV/tykRwfWD2Zy4ofurNZuqd39atfc0Vu8LbrNNsg7ZmU7zqXhFTOHkWV5qGDz/PPVBNG/d3WxGt8Ck7IdBJqKHU/TRA3l1tgc6mWbTGfvwepHwUutZoKfUPwTw/bu7FlABCtM5Dvtw5OuW7v/tuXErKlOvQ4xj+H16WN8Y2ZKW+W+mu+XIr8M+2sh2mgIZ2S5OuyfChIk1OvLFiAcKbc59FtcITAPwxmUNMT5WVFc9Jui5xG89zjEbhXWkGuS5og2gMxizrsPqetrrrsuMAQ/ZOPjvmjSi/3FPh4kWh//Kb/WGisNVH3c14cJZ+oAizLPQG6j5k//TeYQsEbdjOr1AIXaSYVUaCqyZLOgqPWfqiK+pcitANOTaae129yfdfNhvxkn3D79fy3gYI1QpkjTgwptmsUMy4qu5Sn5uNAAs/L1L1UZqAbNx3gLJZSuPFDGxWrC4qU4=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
