k8sServiceHost: k8s.harrytang.com
k8sServicePort: 6443
kubeProxyReplacement: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  enforceHttps: false
  enableProxyProtocol: false
  service:
    type: NodePort
    insecureNodePort: 32080
    secureNodePort: 32443
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
  enableProxyProtocol: false
nodePort:
  enabled: true
hostPort:
  enabled: true
externalIPs:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.1.0.0/16
socketLB:
  enabled: true
  hostNamespaceOnly: false
bpf:
  masquerade: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
