apiServer:
  certSANs:
    - k8s.harrytang.com
  extraArgs:
    - name: encryption-provider-config
      value: /etc/kubernetes/enc/enc.yaml
  extraVolumes:
    - hostPath: /etc/kubernetes/enc
      mountPath: /etc/kubernetes/enc
      name: enc
      pathType: DirectoryOrCreate
      readOnly: true
apiVersion: kubeadm.k8s.io/v1beta4
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: k8s.harrytang.com:6443
controllerManager:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
dns: {}
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      - name: listen-metrics-urls
        value: http://0.0.0.0:2381
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.31.2
networking:
  dnsDomain: cluster.local
  podSubnet: 10.1.0.0/16,fd01::/64
  serviceSubnet: 10.96.0.0/16,fd98::/108
proxy: {}
scheduler:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
