---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: kube-system
spec:
  interval: 24h
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '^0.3.2' # this is chart version, not cloudflared version
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: kube-system
      interval: 24h
  values:
    replicaCount: 2
    image:
      tag: '2025.2.0'
    cloudflare:
      tunnelName: pi-k8s
      tunnelId: b32df1b7-6f82-4e59-8785-d3533750f7c6 # CNAME of the tunnel: b32df1b7-6f82-4e59-8785-d3533750f7c6.cfargotunnel.com
      secretName: tunnel-credentials
      enableWarp: true
      ingress: # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/origin-configuration/#tls-settings
        # - hostname: dash.harrytang.com
        #   service: https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard:443
        #   originRequest:
        #     noTLSVerify: true
        - hostname: storage.harrytang.com
          service: http://longhorn-frontend.longhorn-system:80
        - hostname: prometheus.harrytang.com
          service: http://kube-prom-stack-kube-prome-prometheus.observability:9090
        - hostname: grafana.harrytang.com
          service: http://kube-prom-stack-grafana.observability:80
        - hostname: alerts.harrytang.com
          service: http://kube-prom-stack-kube-prome-alertmanager.observability:9093
        # # - hostname: kiali.harrytang.com
        #   service: http://kiali.istio-system:20001
        # - hostname: jaeger.harrytang.com
        #   service: http://tempo.observability:16686
        - hostname: dbeaver.harrytang.com
          service: http://dbeaver.default:8978
        # - hostname: nats.powerkernel.net
        #   service: http://nats-headless.nats-system:8222
        # - hostname: s3.harrytang.com
        #   service: http://minio.nextcloud:80
        #   # originRequest:
        #   #   noTLSVerify: true
        - hostname: minio.harrytang.com
          service: https://nextcloud-console.nextcloud:9443
          originRequest:
            noTLSVerify: true
        # originRequest:
        #   noTLSVerify: true
        # - hostname: wai.harrytang.com
        #   service: http://wai.default:80
        - hostname: nextcloud.harrytang.com
          service: http://nextcloud.nextcloud:8080
