---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: kube-system
spec:
  encryptedData:
    credentials.json: AgBE4c/eVH1cdGMYMT3b2uJtw8UN5wl/XCoU6CpZuPd2csRPyB1trdASakPY6lT3c0kfi9vqGRfAOMu/8E82//gCU6aFnsizkVRPXkM3dy6uORlxa1mvTNPAXHiXVtyePh9XlVGtZZ4c/xJej2GMurCSt01BUSbHFB3ykWq9q1vm4v5gi2whsL6ejCxnCh1EhZDLRnszjR42xf/28GB3GtZwtSq/1ViWyTNSomZRVqbTRGpHieyCccy9/tPurDMO702j/KujrJt4TUg1gDTaTZghhv3fUe/bDWBCfJlxdDgOtblWp036W9THG85dUTvs1aPymKCbL6JOCA8PHFWOvGUM/cY+WdyMgbqgfmUmeBx/kRAlQ4Uk+O/aHTNOt3MoWt/N3frlQcydBDmAvnyuzs3MbO+z+eMkd/nfm3fi6tqstms2C6naQvlYmqJBHS4DdDBSEjCqmhStSgZRL1nyIl7vLgAvvoHy7TOSAXSlbbErpRbf3z61kTjIDqsMskZKeD8VRyW94cxzuaTP+2eGYjI8rzCbS0P6zOl1kSax6BgA5xHEj+yT9PzV9FjZleXhYRHXE+BuyO4+1WtpJ8pQQUykTmRXrr39WKh7cPaElpqIAQOwDXFNIJ5Vz8UDkrhU8K3U+dCXB4vVM7ju+7ya/x38hDZ6C9T+FzjRtn4CMGWrdWTCUK44RXxWlmGic43GUFx7ct/s2/um2mhu1uthdp99ino0NhyzbMDhL29gFMGSXQm+UDd9rbnhNDklvPU2ff27SWLsMWmrLoAj10HvqyACbRTQJ3XiM9DYnuoz9b5B3wqPYDy3GQ+uNd6wCDIVE9XROmPchKpQa1ku/08TDfzh00nj+zDHxtExMBXUBgNSAdj7APKY0TRLRe2BZoTGmD8DuFqfk5ph3Js2Ex65p0pgoQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: kube-system
