---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 24h
  chart:
    spec:
      chart: ingress-nginx
      version: '^4.11.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 24h
  values:
    controller:
      kind: DaemonSet
      hostPort:
        enabled: true
      ingressClassResource:
        name: public
        default: true
      config: { use-forwarded-headers: 'true' }
      extraArgs:
        publish-status-address: 127.0.0.1
        ingress-class: public
      service:
        enabled: false
