apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: '^1.14.4'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 24h
  values:
    crds:
      enabled: true
    extraArgs:
      - --enable-gateway-api
