---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb
  namespace: nextcloud
spec:
  encryptedData:
    mariadb-password: AgCdhk1x8jr7tkv3HAxA3sG1D8qPslliPBv6C2mk2VR5pLUm1L/tEK+fJj+HEe2y2umofCue3O55W2e/a1ngaSGZjLZSsPsZ6PnGOL/3yyfuwsouEnzp3m7WnmJTv+UVpk+j2o61HMnMgxsxtruO1aHmqMfTE7qnX0EQsfVT4NpldJVIKk6pjFa+IS+/Ozc3b+AlvEvO4IWB5xWhakuL6VG/F2FAMaY22JO7dq1lxvBdxKAs/f3fVD/f5aLTWPQlkQkqiPR16hjGX0K8Txv6wcekeDOIsvgD0bECSrVfD/2FzUNOIdt/PnFbnOa5o3CMB1+6V9JaN3HucMZKtzV2bkL+ZsaAXbtXCjdO1hJC3AUIXMSGAU4Wrvx2reEeurdnysErKxuT54I5WLq1wdZ/ztxl/PXJR5XSpLRP15RSKECnlS/Jxv/mkD1mUAvmm8z2rgQ7QtyDgFjtIqI/Kv1MTgi7wJDk6T2ndc+r+B3ITe7mavz7LPIfv5NGhW8E6bhsk8GbpaQvtSK+C6bdJxxX+wQd8bnZFa/Pw+BfKswgxzdZ7hblLMqSw/jSnWXIVCedaH4jY8zVY2Cb5MLl95QNXRQOPo7p/9YtY9hxu18entf6Lth9rythv55wVgdG6y3smI3vU3kU9dZkxyvclbpgtHGmxc2Py6IA3dmyKq6tzY0vq/cB+gIFQGhS9IwxBaRSBEA5LRgByakgYs/8p6ZRDQ8NSO9UUGTOpzQb6TxULegtiQ==
    mariadb-username: AgBJXwNEnJ9b+rpLRW68tb99SfzqX/uUb+uypYTrW3mqsxIdT/oZKfSISahaCsbCTc9tkHPymxBZOa0CaLv0VF1I3dKom8Me+GoxDQ/PAbszszzgrgeM+FDfcuHFp3c5QeS/AfbB5MJDC4zhSQ5tKg2QuTpwsacrv5/+s2G/J2ycFJYrOzDVNxf6tAY7ohKl4b8xiI6HfukKwhzIN8HBD2JVSTM1S24MbVXaEEARB0DzjH4Gb9kEylY8O+vrB43RgEyppS5HdHd3rAmKQ6E6ZGhIGS9qvc9Qpf7KV1Sjjo3bco8EaOlGDSYlvp8kiKLavu/vAfobzQDRC2Clv4yxWMn/rUrd9+pIa1cLRllWT5Hx//DTpz78Y8ZAkz3O4mmAUvIeR7m8GRpFF2653wsowl52qxJwrfvkj1ARMnnDPLMDM4EZ9jPFmbkEQ6n57FcnK9NSbHWmrWK5mf31kC7FE6LkKREDqKcU8BI0cuyHaxe8p+C9jYKLHeD/1j9u4HrX3gOgMz8qQyD/+NkonlbjK3WdiOjL+RrDHAWjqu39qXbFt3VSL5JcKT1MIWvKE2tnqc8j4295m55KboJgA5Q0RsC6AaHBPalXuELOav1435yJoOSXuRB/GCtF9RT3XmGNgy2sXrmLXizWUmkOsdDS8VbDU98lx3i4O5lqlC+juPCmIBQ4U5D6y7OpaROaJX4UmvBxJnhMuoamKZI=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb
      namespace: nextcloud
