---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-env-configuration
  namespace: nextcloud
spec:
  encryptedData:
    config.env: AgCFs5TQjDmfvlG9ivIiGnm2bOTV6U5cStABlRbpv9w2MfzBslk8R7r+/YrdKEc2ndXD9qShhlKJMGjLLTNdtSJNQ4k0o+VLgnlOoJBR/t9vd4WdkdSLcz9Kex258/UPp9AyDxgUwMXZ95ujC3nD31l6PQruVlV8yRddTFFp/78aBI7cbz0Ao51tVDUCDOxa5MDUsKcaXBl+IpuGrn5BSIyO0XmzShI//Wuz6engzuFaFJwp5NkW/TIIWxVHizIKO1aEmcObY8Y0dKavm3m4jAh9Ztj1SOMoENsBQsDbJZIxsB2MwRl3VAq0YEM4JBJloI9NT0xf5Qm5haKzJ/MpqBgy/ggsxrJiGOKw1iSN459T8ELQDs6xOFy9gHW912mhq+5V84tiJei0AW8Wdv4q8HAIC6srzxO466PgARir/82A8xF54nmFzPEAO8bzSjuZxmCHsj3O1ltUiU74lGS0TK8U/SXzKKXeHgelg5pn1vCwHfzoK0CQ0uCLbr6mOI7nlwqxwo/Toz4FD2VZMUfDyt3MSOUR9ag9VN1SWQHhacHQt2Upb3/COY7bUO/AfECkJPxxgfKsGXySYw3x5xLzGY9u/9WPpy7Tw7lhsR2CqCogmvTFH/nI9mBAPtqgZtIIMZnMB5OW5+6PmistGLlSgOWUls4mi7Ren6VAMPCzaau+slbN3sSptM1Q1PfdqIFZG+bn7cslKSwKi/3ht8ETcSII2NN+ozoNiUsRcNMQH91Q33cXbG/w0CtWSPuVLzaRcPnFZAB8v4J9jxaXPrj9byFwNlGlExpkXZRV0GsDCJiz85ZHAv0G
  template:
    metadata:
      creationTimestamp: null
      name: minio-env-configuration
      namespace: nextcloud
