---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: kube-system
spec:
  encryptedData:
    credentials.json: AgCGVwhm6RRBRV+YRKKPeko9FWwE/9SeuE0iVFio9hCE8HChXkk2dAeL7zRskOFVdcdT4yegUDJq847fwK4mdrIQBvPR9fYM4JxEiV2vOABi4lppsD8sO5xDYuaXDmJIdUoUoa/rqSFXH/dTT+vziTbSFMh8m7bweVMgtZBPnnAFfPUqv+FidU5guJjyp1ptqMiyRoglmUOn1TO8L/Cqu3Kys1HNeTczqJ/VP1uxyguxoeuxFZqgS1ZDWy0g8i97Cwc/i0u8V6UPc9HV+nOvd3aabQoP3yTdhdg/MGBXkj2fVXlzmfDeTR27sXBEvhKkxYoGbv9NmhSDmb1p2VqMfrUtFj57WqlzaO2soHxyE1YO7+zijnkYBURSBdFqOjb2I28pbGvb2m8NEgbWE/UfHhNpxORbcYETZGjLhY2AGDoeo4fuQqqBfB08Ltvbm9sW95AmO0k5uqo+5/jFyrSeCML7Z2eQ1swE1p8VnMPjQtuZR+qewgqOAtLLF8wFu96UiR6hug0S9WIHQpLsLklA86ROZ5rzDoTQduzaluTE1S4AZt81Lw2Rb/S2XRgLgpGU/5HYM90mMdpHTD3HgmRZob1peFbXPH0m84T6RddU3RgI7N/fp62JWEjMvZ5U4So99yo3gO07NdjrfQPAuj41erf96XRWBUxjq3Rsit3fYpsenOHddYLZLJFjh/A8IEjEbhQdzCqwSnNz9jdF2GCHDwwLkyygz1GxMLCw7YC0UadJU0tSsWMy8inPXte9iDA5a46B4vW1/6n+t1iPKSoaEe77YnsOA32Eaiujk0MaMHX4L2IRDUiCSbkZtHSxpz3bGMBm7eSM65ugbIRq/+lpFCq8bh+Mu4c8kMtlYq7JL81X5x6zamoFGP/RWL5mpAnXuTnNKFVYOqZszFVDujlk4nIoIQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: kube-system
