---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: kubelet-csr-approver
      version: '^1.2.3'
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: kube-system
      interval: 24h
  values:
    providerRegex: '^(pi)\d+$'
    bypassDnsResolution: 'true'
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 24h
  url: https://postfinance.github.io/kubelet-csr-approver
