---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: kube-system
spec:
  interval: 24h
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '^0.3.2' # this is chart version, not cloudflared version
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: kube-system
      interval: 24h
  values:
    replicaCount: 2
    image:
      tag: '2025.8.1' # https://hub.docker.com/r/cloudflare/cloudflared/tags
    cloudflare:
      tunnelName: pi-k8s
      tunnelId: b32df1b7-6f82-4e59-8785-d3533750f7c6 # CNAME of the tunnel: b32df1b7-6f82-4e59-8785-d3533750f7c6.cfargotunnel.com
      secretName: tunnel-credentials
      enableWarp: true
      ingress: # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/origin-configuration/#tls-settings
        # - hostname: maxscale.harrytang.com
        #   service: http://maxscale-galera-gui.nextcloud:8989
        - hostname: storage.harrytang.com
          service: http://longhorn-frontend.longhorn-system:80
        - hostname: prometheus.harrytang.com
          service: http://kube-prom-stack-kube-prome-prometheus.observability:9090
        - hostname: grafana.harrytang.com
          service: http://kube-prom-stack-grafana.observability:80
        - hostname: alerts.harrytang.com
          service: http://kube-prom-stack-kube-prome-alertmanager.observability:9093
        # # - hostname: kiali.harrytang.com
        #   service: http://kiali.istio-system:20001
        # - hostname: jaeger.harrytang.com
        #   service: http://tempo.observability:16686
        # - hostname: dbeaver.harrytang.com
        #   service: http://dbeaver.default:8978
        # - hostname: nats.powerkernel.net
        #   service: http://nats-headless.nats-system:8222
        - hostname: s3.harrytang.com
          service: http://minio.s3.svc.k8s.harrytang.com:80
          # originRequest:
          #   noTLSVerify: true
        - hostname: minio.harrytang.com
          service: http://s3-console.s3.svc.k8s.harrytang.com:9090
          # originRequest:
          #   noTLSVerify: true
        # - hostname: wai.harrytang.com
        #   service: http://wai.default:80
        # - hostname: nextcloud.harrytang.com
        #   service: http://nextcloud.nextcloud:8080
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: kube-system
spec:
  encryptedData:
    credentials.json: AgBE4c/eVH1cdGMYMT3b2uJtw8UN5wl/XCoU6CpZuPd2csRPyB1trdASakPY6lT3c0kfi9vqGRfAOMu/8E82//gCU6aFnsizkVRPXkM3dy6uORlxa1mvTNPAXHiXVtyePh9XlVGtZZ4c/xJej2GMurCSt01BUSbHFB3ykWq9q1vm4v5gi2whsL6ejCxnCh1EhZDLRnszjR42xf/28GB3GtZwtSq/1ViWyTNSomZRVqbTRGpHieyCccy9/tPurDMO702j/KujrJt4TUg1gDTaTZghhv3fUe/bDWBCfJlxdDgOtblWp036W9THG85dUTvs1aPymKCbL6JOCA8PHFWOvGUM/cY+WdyMgbqgfmUmeBx/kRAlQ4Uk+O/aHTNOt3MoWt/N3frlQcydBDmAvnyuzs3MbO+z+eMkd/nfm3fi6tqstms2C6naQvlYmqJBHS4DdDBSEjCqmhStSgZRL1nyIl7vLgAvvoHy7TOSAXSlbbErpRbf3z61kTjIDqsMskZKeD8VRyW94cxzuaTP+2eGYjI8rzCbS0P6zOl1kSax6BgA5xHEj+yT9PzV9FjZleXhYRHXE+BuyO4+1WtpJ8pQQUykTmRXrr39WKh7cPaElpqIAQOwDXFNIJ5Vz8UDkrhU8K3U+dCXB4vVM7ju+7ya/x38hDZ6C9T+FzjRtn4CMGWrdWTCUK44RXxWlmGic43GUFx7ct/s2/um2mhu1uthdp99ino0NhyzbMDhL29gFMGSXQm+UDd9rbnhNDklvPU2ff27SWLsMWmrLoAj10HvqyACbRTQJ3XiM9DYnuoz9b5B3wqPYDy3GQ+uNd6wCDIVE9XROmPchKpQa1ku/08TDfzh00nj+zDHxtExMBXUBgNSAdj7APKY0TRLRe2BZoTGmD8DuFqfk5ph3Js2Ex65p0pgoQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: kube-system
